POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "johndoe@example.com",
    "phone": "1234567890",
    "password": "password123",
    "confirmPassword": "password123"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
"password": "password123"
}

